sudo: false
language: python
cache:
  directories:
  - "~/.cache/pip"
python:
- "2.7"
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
- flake8 siggen/
- pytest
- bin/run_cmd_tests.sh
